#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V
#$ -N LLZ
#$ -P cr_liion_materials
#$ -l excl=true
#$ -l h_rt=10:00:00
#$ -q regular
#$ -pe openmpi 10

MPI_CMD="mpirun"
LAMMPS=$LAMMPS_COMMAND
$MPI_CMD $LAMMPS < LLZ.input